- README.md
Expands on errors:
* States that they are the originally thrown error, with additional properties
* Adds `entity.parse.failed`
> Expands Errors and adds 'entity.parse.failed'

- .github/workflows/ci.yml
- HISTORY.md
- package.json
I used a `^` here, since it's a very universal best practice to allow consumers to automatically get the latest bugfixes and security patches.
(I otherwise modeled this after a0ac3e9eb8ad507ae4d35fa1e86d9e6889fbf57f, which is unreleased since March 2020)
I'll remove the `^` if needed; either way I'm hoping for a rapid release so our app can dedupe the multiple copies of `qs` in the tree that we have due to `body-parser` not using a range for `qs`.
> deps: qs@6.10.3

- .github/workflows/ci.yml
- test/body-parser.js
This PR fixes [nyc](https://github.com/istanbuljs/nyc) version to 14.1.1 when running tests in node 8 or node 9. `nyc 15.x `requires a `yargs` package version that requires node >=10.
I've also added the latest versions of node (20, 21 and 22) to the matrix.
Related to https://github.com/jshttp/http-errors/issues/108
> ci: fix errors in ci github action for node 8 and 9

- .github/workflows/ci.yml
[In line with the rest of the project](https://github.com/expressjs/express/pull/5595), we intend to drop support in the next majors for all but current LTS.
> Drop support for less than LTS node versions in v2

- README.md
- lib/types/urlencoded.js
Following up from https://github.com/expressjs/body-parser/pull/326
> Also use the qs module for the simple parser

- README.md
Adding the OSSF Scorecard badge would be great, just like it was done in the express repository
> Add OSSF Scorecard badge

- lib/types/urlencoded.js
Removes the redundant check for v1 and aligns behavior with 2.0.0.
> Remove redundant depth check

- lib/read.js
- test/json.js
- test/raw.js
- test/text.js
- test/urlencoded.js
with the minimum supported node version set to v18 we can remove the brotli support check as it was added in v11.7.0 and v10.16.0
https://nodejs.org/docs/latest/api/zlib.html#zlibcreatebrotlidecompressoptions
> fix: remove brotli support check

- HISTORY.md
- lib/read.js
- package.json
The [`unpipe`](https://www.npmjs.com/package/unpipe) package was used to unpipes all destinations from a given stream.
Taken from the unpipe readme:
> With stream 2+, this is equivalent to stream.unpipe(). When used with streams 1 style streams (typically Node.js 0.8 and below), this module attempts to undo the actions done in stream.pipe(dest).
As our minimum supported Node version is v18 the `unpipe` package is no longer needed.
> fix: remove unpipe package and use native unpipe method

- package.json
This PR removes the unused `methods` package from `devDependencies`. After reviewing the codebase, i think that `methods` is no longer required or used anywhere in the project.
> Remove unused devDependency `methods`

- HISTORY.md
- package.json
**Plan to release it on Oct 30**
* remove `unpipe` package and use native `unpipe()` method
* fix: update package.json engines field to reflect minimum supported node version by @Phillip9587 in https://github.com/expressjs/body-parser/pull/541
* fix: remove brotli support check by @Phillip9587 in https://github.com/expressjs/body-parser/pull/542
* fix: remove unpipe package and use native unpipe method by @Phillip9587 in https://github.com/expressjs/body-parser/pull/543
* Remove unused devDependency `methods` by @Phillip9587 in https://github.com/expressjs/body-parser/pull/548
* ci: updated github actions ci workflow by @Phillip9587 in https://github.com/expressjs/body-parser/pull/546
* @Phillip9587 made their first contribution in https://github.com/expressjs/body-parser/pull/541
**Full …
> Release: 2.0.2

- .github/workflows/ci.yml
Add Node.js v23 to the CI Pipeline for the `1.x` branch and fix the branch filter for the 1.x ci pipeline.
> ci: add support for Node.js v23

- package.json
- test/json.js
- test/raw.js
- test/text.js
- test/urlencoded.js
This PR removes the `safe-buffer` package from devDependencies as it's no longer needed. Since we no longer support Node.js versions older than 18.0.0, the native Buffer class now fully handles security concerns. Additionally, there are no instances of `new Buffer(...)` usage in the repository.
> Remove devDependency `safe-buffer`

- test/json.js
- test/raw.js
- test/text.js
- test/urlencoded.js
with the minimum supported node version set to v18 we can remove the AsyncLocalStorage support check as it was added in v13.10.0 and v12.17.0
> test: remove AsyncLocalStorage check

- index.js
This PR replaces the custom caching logic with [Node.js's built-in require cache](https://nodejs.org/api/modules.html#caching). By leveraging the require cache, the codebase is simplified, performance is improved, and maintenance overhead is reduced. The custom logic has been removed, and the parser loading now relies on `require`.
> perf: use the node require cache instead of custom caching

- .github/workflows/ci.yml
Added `fail-fast: false` to the job strategy matrix to ensure that the tests run on all node versions even if one of them fails.
> ci: disable fail-fast in CI workflow

- HISTORY.md
- lib/read.js
- test/body-parser.js
- test/json.js
- test/raw.js
- test/text.js
- test/urlencoded.js
Align with changes introduced in expressjs/express#6236 by prefixing all built-in Node.js module imports with 'node:'.
Reference: https://github.com/expressjs/express/pull/6236
Taken from that PR: 
> Since v5 relies on node >= 18, this is now possible (since v16, v14.18.0 [1](#user-content-fn-1-187b236bd1bd1a27071fe304ad924f75) [2](#user-content-fn-2-187b236bd1bd1a27071fe304ad924f75)).
> 
> It's functionally irrelevant:
> 
> 1. It's not required for CJS nor ESM (with a few exceptions [3](#user-content-fn-3-187b236bd1bd1a27071fe304ad924f75))
> 2. It has no performance promises
> 
> However, there are upsides to this approach:
> 
> 1. It brings clear boundaries to what's a built-in and what's an external dependency
> 2. It reduces the risk of importing unwanted deps where a built-in is …
> refactor: prefix built-in node module imports

- lib/read.js
- package.json
The [`destroy`](https://www.npmjs.com/package/destroy) package was was used to handle stream destruction across legacy Node.js versions (>=0.8), addressing bugs in specific versions. Since we now officially support only Node.js 18 and newer, we can safely remove this dependency and replace it with a direct call to `stream.destroy()`.
> fix: remove obsolete dependency `destroy`

- package.json
- test/support/env.js
The `test/support/env.js` file contained the definition of an environment variable which was only used to silence [`depd`](https://www.npmjs.com/package/depd) during tests. Since `depd` is not used anymore, we can safely remove the file.
The `NO_DEPRECATION` environment variable is documented here: https://github.com/dougwilson/nodejs-depd?tab=readme-ov-file#processenvno_deprecation
> cleanup: remove obsolete test env file

- HISTORY.md
- package.json
This PR addresses the issue of multiple versions of the `debug` package being installed when using Express v5, which currently results in **four different versions** of `debug`. By updating the `debug` dependency within `body-parser`, we can eliminate one of these redundant versions.
[Dependency Graph for Express v5](https://npmgraph.js.org/?q=express%405)
Related to: 
* https://github.com/expressjs/express/pull/6313
* https://github.com/pillarjs/finalhandler/pull/78
> chore(deps): update `debug` to ^4.4.0

- .github/workflows/ci.yml
The same has been done for the main express repo: [`expressjs/express/.github/workflows/ci.yml`](https://github.com/expressjs/express/blob/master/.github/workflows/ci.yml)
> ci: separate lint step

- test/urlencoded.js
We have a test that was being skipped, and I don't think there was any reason why it should be skipped.
> fix: remove skip of test

- package.json
The `lcov` reporter generates the `lcov.info` file and a html report. We can skip creating the html report and use the `lcovonly` reporter.
> ci: use `lcovonly` reporter for the `test-ci` script

- README.md
This PR is raised to update the ReadMe file to mention the use of "const" instead of "var" in the example code provided.
> fix(docs): replace var with let or const in ReadMe

- lib/types/urlencoded.js
- package.json
Now that body-parser targets Node.js 18, we can finally use String.split to count all the `&`s in `parameterCount` body. This makes the function roughly 2x faster in Chrome/Node.js engine (and about 2.5x faster in Safari/Bun engine), according to this jsperf: https://jsperf.app/niqepi/2
Fun fact: if you run this jsperf in Firefox, the old implementation will get speeds unmatched by any other engine, while the _new_ one will be roughly 7x slower. Thankfully, that's only the case in Firefox.
a
> Refactor parameterCount to optimize performance

- lib/types/json.js
- lib/types/raw.js
- lib/types/text.js
- lib/types/urlencoded.js
This PR is a cleanup of the options handling in all 4 middleware functions. The changes primarily involve using optional chaining.
Follow up to #551
> refactor: cleanup parser options

- HISTORY.md
- package.json
* test: remove `--bail` from test script by @Phillip9587 in https://github.com/expressjs/body-parser/pull/583
* ci: separate lint step by @Phillip9587 in https://github.com/expressjs/body-parser/pull/582
* fix: remove skip of test by @bjohansebas in https://github.com/expressjs/body-parser/pull/589
* ci: use `lcovonly` reporter for the `test-ci` script by @Phillip9587 in https://github.com/expressjs/body-parser/pull/584
* docs: remove security file by @bjohansebas in https://github.com/expressjs/body-parser/pull/590
* fix(docs): replace var with let or const in ReadMe by @Binilkks in https://github.com/expressjs/body-parser/pull/581
* chore: update test dependencies by @Phillip9587 in https://github.com/expressjs/body-parser/pull/585
* dep: upgrade iconv-lite to ^0.6.3 by @aqeelat in …
> Release 2.2.0

- .github/workflows/codeql.yml
Adds CodeQL Scanning for Github Workflows and Actions.
Docs: https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#changing-the-languages-that-are-analyzed
> ci: add codeql github workflows scanning

- .github/workflows/codeql.yml
This PR updates the CodeQL config to exclude the `test` directory from scans. Scanning the `test` directory results in false positives. A long list of false positives makes it harder to interpret the result of CodeQL runs. I think we want to scan user-exectuable code, but not our tests.
> ci: update CodeQL config to ignore the test directory

- lib/types/raw.js
- lib/types/text.js
- lib/utils.js
- Replaces duplicate `parse()` functions in the `raw` and `text` parser that just pass-through the value with a shared passthrough in `utils.js`
- Reduces memory overhead when using multiple instances of the same middleware in an application by eliminating function duplication per middleware instance
- Reduces closure overhead by removing captured parse functions
- Allows V8 to optimize and potentially inline the function
> refactor: optimize raw and text parsers with shared passthrough function
